/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Auto generated by vite-plugin-dir2json
declare module "*C:/Users/Walid/Documents/GitHub/baxterverse/next-ui/src/i18n?dir2json&ext=.json&1" {
  const json: {};
  export default json;
}

declare module "*dir2json" {
  const json: any;
  export default json;
}